version: '3'

services:
  lyra-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    networks:
      - lyraappnet

    
  lyra-api:
    restart: unless-stopped
    build: .
    environment:
      - ConnectionStrings:LyraDev=Server=lyra-sql,1433;Database=LyraDocker;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 64236:80
    networks:
      - lyraappnet     
    links:
      - lyra-sql
    depends_on:
      - lyra-sql
      
networks:
  lyraappnet:
    driver: bridge

        