version: '3'

services:
  lyra-ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
        ACCEPT_EULA: Y
        MSSQL_SA_PASSWORD: rs2Password
        MSSQL_PID: Express
    ports:
      - 1433:1433
    networks:
      - lyraappnet
    
  lyra-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:local=Server=lyra-ms-sql-server,1433;Database=170097Docker;User=Sa;Password=rs2Password;ConnectRetryCount=0
    ports:
      - 65094:5050
    networks:
      - eventiappnet     
    links:
      - lyra-ms-sql-server
    depends_on:
      - lyra-ms-sql-server
      
networks:
  eventiappnet:
    driver: bridge

        